import { describe, it, expect } from 'vitest';
import { generateThemeCSS } from './theme-to-css.util';
import { ThemeStyles, HSLAdjustments } from '@codename/api';

describe('theme-to-css.util', () => {
  describe('generateThemeCSS', () => {
    const mockStyles: ThemeStyles = {
      light: {
        'background-primary': '#ffffff',
        'text-primary': '#000000',
        'accent-color': 'oklch(0.6 0.2 250)',
        'border-color': 'hsl(0, 0%, 80%)',
      },
      dark: {
        'background-primary': '#000000',
        'text-primary': '#ffffff',
        'accent-color': 'oklch(0.6 0.2 250)',
        'border-color': 'hsl(0, 0%, 20%)',
      },
    };

    const defaultAdjustments: HSLAdjustments = {
      hueShift: 0,
      saturationScale: 1,
      lightnessScale: 1,
    };

    it('generates valid CSS with :root and .dark selectors', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      expect(result).toContain(':root {');
      expect(result).toContain('.dark {');
      expect(result).toContain('--background-primary:');
      expect(result).toContain('--text-primary:');
      expect(result).toContain('/* Generated by Design Studio */');
    });

    it('includes light mode variables under :root', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // Find the :root section
      const rootMatch = result.match(/:root \{([\s\S]*?)\}/);
      expect(rootMatch).toBeTruthy();

      const rootContent = rootMatch![1];
      // Colors are transformed by adjustColorByHSL to oklch
      expect(rootContent).toContain('--background-primary:');
      expect(rootContent).toContain('--text-primary:');
      expect(rootContent).toContain('--accent-color:');
      expect(rootContent).toContain('--border-color:');
    });

    it('includes dark mode variables under .dark', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // Find the .dark section
      const darkMatch = result.match(/\.dark \{([\s\S]*?)\}/);
      expect(darkMatch).toBeTruthy();

      const darkContent = darkMatch![1];
      // Colors are transformed by adjustColorByHSL to oklch
      expect(darkContent).toContain('--background-primary:');
      expect(darkContent).toContain('--text-primary:');
      expect(darkContent).toContain('--accent-color:');
      expect(darkContent).toContain('--border-color:');
    });

    it('properly formats CSS variables with indentation', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // Each variable should be on its own line with 2-space indentation
      expect(result).toContain('  --background-primary:');
      expect(result).toContain('  --text-primary:');
    });

    it('trims whitespace from output', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // Should not have leading/trailing whitespace
      expect(result).toEqual(result.trim());
    });

    it('handles oklch color values', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // After adjustColorByHSL transformation, oklch colors are still present
      // (though potentially modified by the adjustment)
      expect(result).toContain('oklch');
    });

    it('handles hsl color values', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // HSL colors are transformed by adjustColorByHSL
      // Just verify the CSS contains border-color variables
      expect(result).toContain('--border-color:');
    });

    it('handles hex color values', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // Hex colors are transformed by adjustColorByHSL to oklch
      // Just verify the CSS contains the variable names
      expect(result).toContain('--background-primary:');
      expect(result).toContain('--text-primary:');
    });

    it('applies HSL hue shift adjustment', () => {
      const adjustments: HSLAdjustments = {
        hueShift: 30,
        saturationScale: 1,
        lightnessScale: 1,
      };

      const result = generateThemeCSS(mockStyles, adjustments);

      // Colors should be adjusted (we can't test exact output without the actual adjustColorByHSL)
      // but we can verify the function completes without error
      expect(result).toBeTruthy();
      expect(result).toContain('--accent-color:');
    });

    it('applies HSL saturation scale adjustment', () => {
      const adjustments: HSLAdjustments = {
        hueShift: 0,
        saturationScale: 1.5,
        lightnessScale: 1,
      };

      const result = generateThemeCSS(mockStyles, adjustments);

      expect(result).toBeTruthy();
      expect(result.length).toBeGreaterThan(0);
    });

    it('applies HSL lightness scale adjustment', () => {
      const adjustments: HSLAdjustments = {
        hueShift: 0,
        saturationScale: 1,
        lightnessScale: 0.8,
      };

      const result = generateThemeCSS(mockStyles, adjustments);

      expect(result).toBeTruthy();
      expect(result).toContain('--background-primary:');
    });

    it('handles empty styles object', () => {
      const emptyStyles: ThemeStyles = {
        light: {},
        dark: {},
      };

      const result = generateThemeCSS(emptyStyles, defaultAdjustments);

      expect(result).toContain(':root {');
      expect(result).toContain('.dark {');
      // Should have empty selectors
      expect(result).toMatch(/:root \{\s*\}/);
    });

    it('handles rgb color values', () => {
      const stylesWithRgb: ThemeStyles = {
        light: {
          'test-color': 'rgb(255, 0, 0)',
        },
        dark: {
          'test-color': 'rgb(0, 255, 0)',
        },
      };

      const result = generateThemeCSS(stylesWithRgb, defaultAdjustments);

      // RGB colors are transformed by adjustColorByHSL
      // Just verify the CSS contains the test-color variable
      expect(result).toContain('--test-color:');
      expect(result.split('--test-color:').length).toBeGreaterThanOrEqual(2); // At least light and dark
    });

    it('generates parseable CSS', () => {
      const result = generateThemeCSS(mockStyles, defaultAdjustments);

      // Basic sanity check that output is valid CSS-like
      expect(result).toMatch(/^\/\*.*?\*\/\s*:root \{[^}]*\}\s*\.dark \{[^}]*\}$/s);
    });
  });
});
