import { ThemeStyles, HSLAdjustments, adjustColorByHSL } from '@codename/api';

/**
 * Utility to generate CSS variables from theme data for container-side injection.
 * Matches the logic used in the frontend Preview component but outputs a full CSS block.
 */
export function generateThemeCSS(styles: ThemeStyles, adjustments: HSLAdjustments): string {
  const generateVariables = (mode: 'light' | 'dark') => {
    const modeStyles = styles[mode];
    let variables = '';
    
    for (const [key, value] of Object.entries(modeStyles)) {
      let finalValue = value;
      
      // Apply HSL adjustments to color properties
      if (typeof value === 'string' && (value.startsWith('oklch') || value.startsWith('#') || value.startsWith('hsl') || value.startsWith('rgb'))) {
        finalValue = adjustColorByHSL(
          value,
          adjustments.hueShift,
          adjustments.saturationScale,
          adjustments.lightnessScale
        );
      }
      
      variables += `  --${key}: ${finalValue};\n`;
    }
    
    return variables;
  };

  return `
/* Generated by Design Studio */
:root {
${generateVariables('light')}
}

.dark {
${generateVariables('dark')}
}
`.trim();
}
