export interface ExtractedService {
  id: string;                    // UUID generated by backend
  name: string;                  // e.g., "Goddess Braids"
  price: number;                 // e.g., 150 (cents)
  duration: number;              // Minutes, e.g., 240 for 4 hours
  category: string | null;       // e.g., "Braids" - can be null if not detected
  confidence: number;            // 0-100 score
  boundingBox?: {                // Optional: where on image this was found
    x: number;
    y: number;
    width: number;
    height: number;
  };
  description?: string;
}

export interface ExtractionWarning {
  type: 'low_confidence' | 'missing_price' | 'unreadable_section';
  message: string;
  affectedServiceIds?: string[];
}

export interface ExtractionError {
  code: 'UNREADABLE_IMAGE' | 'NO_SERVICES_FOUND' | 'TIMEOUT' | 'SERVER_ERROR';
  message: string;
  canRetry: boolean;
  suggestions?: string[];
}

export interface ExtractionResult {
  id: string;                    // Analysis session ID
  services: ExtractedService[];
  categories: string[];          // Unique detected categories
  overallConfidence: number;     // Aggregate confidence 0-100
  sourceImageUrl: string;        // Stored image URL for Screen 1C reference
  processingTimeMs: number;      // For analytics
  warnings: ExtractionWarning[]; // Non-fatal issues
}

export type ExtractionStatus =
  | { phase: 'uploading'; progress: number }
  | { phase: 'enhancing'; progress: number }
  | { phase: 'reading'; progress: number }
  | { phase: 'structuring'; progress: number }
  | { phase: 'complete'; result: ExtractionResult }
  | { phase: 'error'; error: ExtractionError };
